use std::collections::HashMap;
use std::fs;
use std::path::Path;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 3 {
        eprintln!("Usage: obj2rust <input.obj> <output.rs>");
        eprintln!("  Converts an OBJ file (with MTL) to a Rust source file with baked vertex data.");
        std::process::exit(1);
    }

    let obj_path = Path::new(&args[1]);
    let out_path = Path::new(&args[2]);

    let obj_text = fs::read_to_string(obj_path).expect("failed to read OBJ file");

    // Find and parse MTL file
    let mut materials: HashMap<String, [f32; 3]> = HashMap::new();
    materials.insert("default".into(), [0.8, 0.8, 0.8]);

    for line in obj_text.lines() {
        if let Some(mtl_file) = line.strip_prefix("mtllib ") {
            let mtl_path = obj_path.parent().unwrap().join(mtl_file.trim());
            if let Ok(mtl_text) = fs::read_to_string(&mtl_path) {
                parse_mtl(&mtl_text, &mut materials);
            } else {
                eprintln!("warning: could not read MTL file: {}", mtl_path.display());
            }
        }
    }

    // Parse OBJ geometry
    let mut positions: Vec<[f32; 3]> = Vec::new();
    let mut normals: Vec<[f32; 3]> = Vec::new();
    let mut current_material = "default".to_string();

    // Output: interleaved [px, py, pz, nx, ny, nz, r, g, b] per vertex
    let mut vertices: Vec<f32> = Vec::new();

    for line in obj_text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("v ") {
            positions.push(parse_vec3(rest));
        } else if let Some(rest) = line.strip_prefix("vn ") {
            normals.push(parse_vec3(rest));
        } else if let Some(mat) = line.strip_prefix("usemtl ") {
            current_material = mat.trim().to_string();
        } else if let Some(rest) = line.strip_prefix("f ") {
            let color = materials
                .get(&current_material)
                .copied()
                .unwrap_or([0.8, 0.8, 0.8]);
            let face_verts: Vec<([f32; 3], [f32; 3])> = rest
                .split_whitespace()
                .map(|v| parse_face_vertex(v, &positions, &normals))
                .collect();

            // Triangulate (fan from first vertex)
            for i in 1..face_verts.len() - 1 {
                for &idx in &[0, i, i + 1] {
                    let (pos, norm) = face_verts[idx];
                    vertices.extend_from_slice(&pos);
                    vertices.extend_from_slice(&norm);
                    vertices.extend_from_slice(&color);
                }
            }
        }
    }

    let vertex_count = vertices.len() / 9;

    // If the model has no normals, compute face normals
    let has_normals = !normals.is_empty();
    if !has_normals {
        eprintln!("warning: OBJ has no normals, computing face normals");
        compute_face_normals(&mut vertices);
    }

    // Generate Rust source
    let mut out = String::new();
    out.push_str("// Generated by obj2rust — do not edit manually.\n\n");
    out.push_str(&format!(
        "/// Vertex count: {vertex_count} vertices, {} triangles\n",
        vertex_count / 3
    ));
    out.push_str("/// Layout per vertex: [pos_x, pos_y, pos_z, norm_x, norm_y, norm_z, r, g, b]\n");
    out.push_str(&format!("pub const VERTEX_COUNT: usize = {vertex_count};\n"));
    out.push_str("pub const STRIDE: usize = 9; // floats per vertex\n\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const VERTICES: &[f32] = &[\n");

    for tri in 0..vertex_count / 3 {
        out.push_str("    // triangle\n");
        for v in 0..3 {
            let base = (tri * 3 + v) * 9;
            out.push_str(&format!(
                "    {:>9.5},{:>9.5},{:>9.5},  {:>7.4},{:>7.4},{:>7.4},  {:.4},{:.4},{:.4},\n",
                vertices[base],
                vertices[base + 1],
                vertices[base + 2],
                vertices[base + 3],
                vertices[base + 4],
                vertices[base + 5],
                vertices[base + 6],
                vertices[base + 7],
                vertices[base + 8],
            ));
        }
    }

    out.push_str("];\n");

    fs::write(out_path, &out).expect("failed to write output");
    eprintln!(
        "wrote {} vertices ({} triangles) to {}",
        vertex_count,
        vertex_count / 3,
        out_path.display()
    );
}

fn parse_vec3(s: &str) -> [f32; 3] {
    let mut parts = s.split_whitespace();
    let x: f32 = parts.next().unwrap().parse().unwrap();
    let y: f32 = parts.next().unwrap().parse().unwrap();
    let z: f32 = parts.next().unwrap().parse().unwrap();
    [x, y, z]
}

fn parse_face_vertex(
    s: &str,
    positions: &[[f32; 3]],
    normals: &[[f32; 3]],
) -> ([f32; 3], [f32; 3]) {
    let parts: Vec<&str> = s.split('/').collect();
    let vi: usize = parts[0].parse::<usize>().unwrap() - 1;
    let pos = positions[vi];

    let norm = if parts.len() >= 3 && !parts[2].is_empty() {
        let ni: usize = parts[2].parse::<usize>().unwrap() - 1;
        normals[ni]
    } else {
        [0.0, 1.0, 0.0] // placeholder, will be recomputed
    };

    (pos, norm)
}

fn parse_mtl(text: &str, materials: &mut HashMap<String, [f32; 3]>) {
    let mut current = String::new();
    for line in text.lines() {
        let line = line.trim();
        if let Some(name) = line.strip_prefix("newmtl ") {
            current = name.trim().to_string();
        } else if let Some(kd) = line.strip_prefix("Kd ") {
            let color = parse_vec3(kd);
            materials.insert(current.clone(), color);
        }
    }
}

fn compute_face_normals(vertices: &mut [f32]) {
    let vertex_count = vertices.len() / 9;
    for tri in 0..vertex_count / 3 {
        let base0 = tri * 3 * 9;
        let base1 = base0 + 9;
        let base2 = base0 + 18;

        let p0 = [vertices[base0], vertices[base0 + 1], vertices[base0 + 2]];
        let p1 = [vertices[base1], vertices[base1 + 1], vertices[base1 + 2]];
        let p2 = [vertices[base2], vertices[base2 + 1], vertices[base2 + 2]];

        let e1 = [p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2]];
        let e2 = [p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2]];
        let mut n = [
            e1[1] * e2[2] - e1[2] * e2[1],
            e1[2] * e2[0] - e1[0] * e2[2],
            e1[0] * e2[1] - e1[1] * e2[0],
        ];
        let len = (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt();
        if len > 1e-8 {
            n[0] /= len;
            n[1] /= len;
            n[2] /= len;
        }

        for v in 0..3 {
            let base = (tri * 3 + v) * 9;
            vertices[base + 3] = n[0];
            vertices[base + 4] = n[1];
            vertices[base + 5] = n[2];
        }
    }
}
